name: mobx_imc
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  currency_text_input_formatter: ^2.1.10
  flutter:
    sdk: flutter
  flutter_mobx: ^2.1.0+1
  intl: ^0.18.1
  mobx: ^2.2.1
  syncfusion_flutter_gauges: ^23.1.41

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
